// Code generated by \"eventhandlers\"; DO NOT EDIT
// See events.go

package ws

import "github.com/robbix1206/discordgo/discord"

// Following are all the event types.
// Event type values are used to match the events returned by Discord.

type ChannelCreate = discord.ChannelCreate
type ChannelDelete = discord.ChannelDelete
type ChannelPinsUpdate = discord.ChannelPinsUpdate
type ChannelUpdate = discord.ChannelUpdate
type Connect = discord.Connect
type Disconnect = discord.Disconnect
type Event = discord.Event
type GuildBanAdd = discord.GuildBanAdd
type GuildBanRemove = discord.GuildBanRemove
type GuildCreate = discord.GuildCreate
type GuildDelete = discord.GuildDelete
type GuildEmojisUpdate = discord.GuildEmojisUpdate
type GuildIntegrationsUpdate = discord.GuildIntegrationsUpdate
type GuildMemberAdd = discord.GuildMemberAdd
type GuildMemberRemove = discord.GuildMemberRemove
type GuildMemberUpdate = discord.GuildMemberUpdate
type GuildMembersChunk = discord.GuildMembersChunk
type GuildRoleCreate = discord.GuildRoleCreate
type GuildRoleDelete = discord.GuildRoleDelete
type GuildRoleUpdate = discord.GuildRoleUpdate
type GuildUpdate = discord.GuildUpdate
type MessageAck = discord.MessageAck
type MessageCreate = discord.MessageCreate
type MessageDelete = discord.MessageDelete
type MessageDeleteBulk = discord.MessageDeleteBulk
type MessageReactionAdd = discord.MessageReactionAdd
type MessageReactionRemove = discord.MessageReactionRemove
type MessageReactionRemoveAll = discord.MessageReactionRemoveAll
type MessageUpdate = discord.MessageUpdate
type PresenceUpdate = discord.PresenceUpdate
type Ready = discord.Ready
type Resumed = discord.Resumed
type TypingStart = discord.TypingStart
type UserUpdate = discord.UserUpdate
type VoiceServerUpdate = discord.VoiceServerUpdate
type VoiceStateUpdate = discord.VoiceStateUpdate
type WebhooksUpdate = discord.WebhooksUpdate
