// Code generated by \"eventhandlers\"; DO NOT EDIT
// See events.go

package ws

import "github.com/robbix1206/discordgo/structures"

// Following are all the event types.
// Event type values are used to match the events returned by Discord.

type ChannelCreate = structures.ChannelCreate
type ChannelDelete = structures.ChannelDelete
type ChannelPinsUpdate = structures.ChannelPinsUpdate
type ChannelUpdate = structures.ChannelUpdate
type Connect = structures.Connect
type Disconnect = structures.Disconnect
type Event = structures.Event
type GuildBanAdd = structures.GuildBanAdd
type GuildBanRemove = structures.GuildBanRemove
type GuildCreate = structures.GuildCreate
type GuildDelete = structures.GuildDelete
type GuildEmojisUpdate = structures.GuildEmojisUpdate
type GuildIntegrationsUpdate = structures.GuildIntegrationsUpdate
type GuildMemberAdd = structures.GuildMemberAdd
type GuildMemberRemove = structures.GuildMemberRemove
type GuildMemberUpdate = structures.GuildMemberUpdate
type GuildMembersChunk = structures.GuildMembersChunk
type GuildRoleCreate = structures.GuildRoleCreate
type GuildRoleDelete = structures.GuildRoleDelete
type GuildRoleUpdate = structures.GuildRoleUpdate
type GuildUpdate = structures.GuildUpdate
type MessageAck = structures.MessageAck
type MessageCreate = structures.MessageCreate
type MessageDelete = structures.MessageDelete
type MessageDeleteBulk = structures.MessageDeleteBulk
type MessageReactionAdd = structures.MessageReactionAdd
type MessageReactionRemove = structures.MessageReactionRemove
type MessageReactionRemoveAll = structures.MessageReactionRemoveAll
type MessageUpdate = structures.MessageUpdate
type PresenceUpdate = structures.PresenceUpdate
type Ready = structures.Ready
type Resumed = structures.Resumed
type TypingStart = structures.TypingStart
type UserUpdate = structures.UserUpdate
type VoiceServerUpdate = structures.VoiceServerUpdate
type VoiceStateUpdate = structures.VoiceStateUpdate
type WebhooksUpdate = structures.WebhooksUpdate
